const API_BASE_URL = process.env.REACT_APP_API_BASE_URL;

const API_ENDPOINTS = {
  LOGINUSER: process.env.REACT_APP_LOGIN_ENDPOINT,
  ADD_CATEGORY: process.env.REACT_APP_ADD_CATEGORY_ENDPOINT,
  GET_ALL_CATEGORIES: process.env.REACT_APP_GET_ALL_CATEGORIES_ENDPOINT,
  ADD_BANNER: process.env.REACT_APP_ADD_BANNER_ENDPOINT,
  GET_ALL_BANNERS: process.env.REACT_APP_GET_ALL_BANNERS_ENDPOINT,
};

export { API_BASE_URL, API_ENDPOINTS };
