const API_BASE_URL = process.env.REACT_APP_API_BASE_URL;

const API_ENDPOINTS = {
  LOGINUSER: process.env.REACT_APP_LOGIN_ENDPOINT,
  ADD_CATEGORY: process.env.REACT_APP_ADD_CATEGORY_ENDPOINT,
  GET_ALL_CATEGORIES: process.env.REACT_APP_GET_ALL_CATEGORIES_ENDPOINT,
  ADD_BANNER: process.env.REACT_APP_ADD_BANNER_ENDPOINT,
  GET_ALL_BANNERS: process.env.REACT_APP_GET_ALL_BANNERS_ENDPOINT,
  UPDATE_BANNER_STATUS: process.env.REACT_APP_UPDATE_BANNER_STATUS_ENDPOINT,
  ADD_PRODUCT: process.env.REACT_APP_ADD_PRODUCT_ENDPOINT,
  GET_ALL_PRODUCTS: process.env.REACT_APP_GET_ALL_PRODUCTS_ENDPOINT,
  UPDATE_PRODUCT_STATUS: process.env.REACT_APP_UPDATE_PRODUCT_STATUS_ENDPOINT,
  UPDATE_PRODUCT_IMAGE: process.env.REACT_APP_UPDATE_PRODUCT_IMAGE_ENDPOINT,
  ADD_BLOG: process.env.REACT_APP_ADD_BLOG_ENDPOINT,
  GET_ALL_BLOGS: process.env.REACT_APP_GET_ALL_BLOGS_ENDPOINT,
};

export { API_BASE_URL, API_ENDPOINTS };


